PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dpv: <https://w3id.org/dpv#>
PREFIX schema: <https://schema.org/>

INSERT {
  GRAPH ?g {
    ?process schema:associatedMedia ?attachmentFile .
  }
}
WHERE {
  GRAPH ?g {
    ?attachmentFile a nfo:FileDataObject .
    ?process a dpv:Process .

    ?attachmentFile nie:isPartOf ?process .

    FILTER NOT EXISTS {
      ?item a schema:ListItem .
      ?item schema:item ?attachmentFile .
    }
  }
}