PREFIX nfo:     <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX nie:     <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dpv:     <https://w3id.org/dpv#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX schema:  <http://schema.org/>

INSERT {
  GRAPH ?g {
    ?process schema:associatedMedia ?attachmentFile .
  }
}
WHERE {
  GRAPH ?g {
    ?attachmentFile a nfo:FileDataObject ;
                    dbpedia:fileExtension ?ext ;
                    nie:isPartOf ?process .
    ?process a dpv:Process .
  }

  FILTER( !(LCASE(STR(?ext)) IN ("bpmn", "vsdx")) )
}
