version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-openproceshuis:latest # FIXME latest in docker compose dev, released here
    volumes:
      - ./config/frontend/add-x-frame-options-header.conf:/config/add-x-frame-options.conf
    labels:
      - "logging=true"
    logging: *default-logging
    restart: always
  identifier:
    image: semtech/mu-identifier:1.10.1
    labels:
      - "logging=true"
    logging: *default-logging
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"},{"variables":[],"name":"clean"}]'
    links:
      - dispatcher:dispatcher
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    logging: *default-logging
    labels:
      - "logging=true"
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
  database:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
  triplestore:
    logging: *default-logging
    labels:
      - "logging=true"
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
  migrations:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
  resource:
    logging: *default-logging
    labels:
      - "logging=true"
    image: semtech/mu-cl-resources:1.23.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:feature-validate-readable-metadata
    labels:
      - "logging=true"
    logging: *default-logging
    links:
      - database:database
    volumes:
      - ./data/files:/share
    environment:
      VALIDATE_READABLE_METADATA: "true"
    restart: always
  bpmn:
    logging: *default-logging
    labels:
      - "logging=true"
    image: lblod/bpmn-service
    volumes:
      - ./data/files:/share
    restart: always
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    labels:
      - "logging=true"
    links:
      - database:database
    restart: always
    logging: *default-logging
  ################################################################################
  # MU SEARCH
  ################################################################################
  search:
    image: nbittich/mu-search:experimental-dense-vector
    links:
      - database:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
    volumes:
      - ./config/search:/config
  hq:
    image: elastichq/elasticsearch-hq
    ports:
      - 5000:5000
  elasticsearch:
    ports:
      - 9200:9200
    labels:
      - "logging=true"
    logging: *default-logging
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    # volumes:
    #   - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    restart: always
