PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu:<http://mu.semte.ch/vocabularies/core/>
PREFIX ext:<http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/973a571a-2944-482f-88f2-d0491aca9859> {
    <http://data.lblod.info/id/persoon/4e273f59-b963-4c96-a157-f540899a3f4c> a foaf:Person ;
      mu:uuid "4e273f59-b963-4c96-a157-f540899a3f4c" ;
      foaf:firstName "Vanden Broele" ;
      foaf:familyName "Vanden Broele" ;
      foaf:member <http://data.lblod.info/id/bestuurseenheden/973a571a-2944-482f-88f2-d0491aca9859> ;
      foaf:account <http://data.lblod.info/id/account/cd7c5e03-3532-4416-a11d-7e6f78641439> .
    <http://data.lblod.info/id/account/cd7c5e03-3532-4416-a11d-7e6f78641439> a foaf:OnlineAccount ;
      mu:uuid "cd7c5e03-3532-4416-a11d-7e6f78641439" ;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
      ext:sessionRole "LoketLB-OpenProcesHuisAfnemer".
  }
}