PREFIX dpv: <https://w3id.org/dpv>
PREFIX proces: <https://data.vlaanderen.be/ns/proces#>

DELETE {
    GRAPH ?g {
        ?s a proces:Proces
    }
}

INSERT {
    GRAPH ?g {
        ?s a dpv:Process
    }
}

WHERE {
    GRAPH ?g {
        ?s a proces:Proces
    }
}