PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/4d79a18a-7a46-4b03-8712-3bcf3467787b>
      rdf:type	<http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode> , <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode> ;
      skos:prefLabel	"Digitaal Vlaanderen" ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"4d79a18a-7a46-4b03-8712-3bcf3467787b" .
    
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/fd4dda91-a6a5-485a-9d49-1378c94a5ff0>
      rdf:type	<http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode> , <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode> ;
      skos:prefLabel	"Vereniging van Vlaamse Steden en Gemeenten" ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"fd4dda91-a6a5-485a-9d49-1378c94a5ff0" .

    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/c4483583-f9fe-4d2f-96f4-47ddb3440d71>
      rdf:type	<http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode> , <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode> ;
      skos:prefLabel	"Leverancier" ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"c4483583-f9fe-4d2f-96f4-47ddb3440d71" .
  }
}