PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu:   <http://mu.semte.ch/vocabularies/core/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX dpv:  <https://w3id.org/dpv#>
PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX oph: <http://lblod.data.gift/vocabularies/openproceshuis/>

INSERT {
  GRAPH ?g {
    ?versionedProcess a dpv:Process ;
                      a ext:VersionedProcess ;
                      mu:uuid ?newUuid ;
                      dct:isVersionOf ?process ;
                      oph:isVersionedResource """true"""^^xsd:boolean .

    ?versionedProcess ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    ?process a dpv:Process .

    FILTER NOT EXISTS {
      ?existingVersion a ext:VersionedProcess ;
                       dct:isVersionOf ?process .
    }

    BIND(STRUUID() AS ?newUuid)
    BIND(IRI(CONCAT("http://data.lblod.info/processes/versions/", ?newUuid)) AS ?versionedProcess)

    ?process ?p ?o .

    FILTER(?p NOT IN(
                    rdf:type,
                    mu:uuid,
                    dct:isVersionOf,
                    ext:hasStatistics
                  ) 
    )
  }
  ?g ext:ownedBy ?eenheid .
}