PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu:   <http://mu.semte.ch/vocabularies/core/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX oph:  <http://lblod.data.gift/vocabularies/openproceshuis/>
PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?versionedConceptualProcess a oph:ConceptueelProces ;
                                a ext:VersionedConceptualProcess ;
                                mu:uuid ?newUuid ;
                                dct:isVersionOf ?conceptualProcess .

    ?versionedConceptualProcess ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    ?conceptualProcess a oph:ConceptueelProces .

    FILTER NOT EXISTS {
      ?existingVersion a ext:VersionedConceptualProcess ;
                       dct:isVersionOf ?conceptualProcess .
    }

    BIND(STRUUID() AS ?newUuid)
    BIND(IRI(CONCAT("http://data.lblod.info/conceptual-processes/versions/", ?newUuid)) AS ?versionedConceptualProcess)

    ?conceptualProcess ?p ?o .

    FILTER(?p != rdf:type)
    FILTER(?p != mu:uuid)
    FILTER(?p != dct:isVersionOf)
  }
}