@startuml
set namespaceSeparator none
class "tasks"
"bpmn-elements" <|-- "tasks"
class "administrative-unit-classification-codes"
"administrative-unit-classification-codes" : label
"administrative-unit-classification-codes" --> "*" "groups" : groups > 
"administrative-unit-classification-codes" --> "*" "processes" : processes > 
class "message-flows"
"message-flows" : source
"message-flows" : target
"bpmn-elements" <|-- "message-flows"
class "accounts"
"accounts" : provider
"accounts" : identifier
"accounts" --> "1" "users" : user > 
class "inclusive-gateways"
"inclusive-gateways" : defaultelement
"inclusive-gateways" : outgoing
"inclusive-gateways" : incoming
"bpmn-elements" <|-- "inclusive-gateways"
class "text-annotations"
"text-annotations" : comment
"bpmn-elements" <|-- "text-annotations"
class "errors"
"bpmn-elements" <|-- "errors"
class "exclusive-gateways"
"exclusive-gateways" : defaultelement
"exclusive-gateways" : outgoing
"exclusive-gateways" : incoming
"bpmn-elements" <|-- "exclusive-gateways"
class "site-types"
"site-types" : label
class "parallel-gateways"
"parallel-gateways" : defaultelement
"parallel-gateways" : outgoing
"parallel-gateways" : incoming
"bpmn-elements" <|-- "parallel-gateways"
class "bpmn-element-types"
"bpmn-element-types" : label
"bpmn-element-types" : key
"bpmn-element-types" : scheme
class "end-events"
"end-events" : incoming
"bpmn-elements" <|-- "end-events"
class "receive-tasks"
"tasks" <|-- "receive-tasks"
class "process-statistics"
"process-statistics" : pdf-downloads
"process-statistics" : png-downloads
"process-statistics" : svg-downloads
"process-statistics" : bpmn-downloads
"process-statistics" : visio-downloads
"process-statistics" : process-views
"process-statistics" --> "1" "processes" : process > 
class "data-object-references"
"data-object-references" : reference
"bpmn-elements" <|-- "data-object-references"
class "sites"
"sites" : site-type-name
"sites" --> "1" "site-types" : site-type > 
"sites" --> "*" "contact-points" : contacts > 
class "participants"
"participants" : process
"bpmn-elements" <|-- "participants"
class "process-groups"
"process-groups" : label
"process-groups" : created
"process-groups" : modified
"process-groups" : status
"process-groups" : scheme
"process-groups" : archived-at
"process-groups" --> "*" "process-domains" : process-domains > 
"process-groups" --> "*" "process-groups" : replaced-groups > 
class "business-rule-tasks"
"tasks" <|-- "business-rule-tasks"
class "contact-points"
"contact-points" : email
"contact-points" : telephone
"contact-points" : fax
"contact-points" : website
"contact-points" : type
class "ipdc-products"
"ipdc-products" : name
"ipdc-products" : product-number
"ipdc-products" --> "*" "processes" : processes > 
class "data-input-associations"
"data-input-associations" : source
"data-input-associations" : target
"data-input-associations" : datainputfor
"bpmn-elements" <|-- "data-input-associations"
class "start-events"
"start-events" : outgoing
"bpmn-elements" <|-- "start-events"
class "conceptual-processes"
"conceptual-processes" : title
"conceptual-processes" : number
"conceptual-processes" : created
"conceptual-processes" : modified
"conceptual-processes" : status
"conceptual-processes" --> "*" "process-groups" : process-groups > 
class "users"
"users" : first-name
"users" : family-name
"users" --> "*" "accounts" : accounts > 
"users" --> "*" "groups" : groups > 
class "service-tasks"
"tasks" <|-- "service-tasks"
class "collaborations"
"bpmn-elements" <|-- "collaborations"
class "processes"
"processes" : title
"processes" : description
"processes" : email
"processes" : created
"processes" : modified
"processes" : status
"processes" : is-blueprint
"processes" : additional-information
"processes" : has-control-measure
"processes" : is-versioned-resource
"processes" --> "1" "groups" : publisher > 
"processes" --> "1" "groups" : creator > 
"processes" --> "1" "process-statistics" : process-statistics > 
"processes" --> "1" "conceptual-processes" : linked-concept > 
"processes" --> "*" "diagram-lists" : diagram-lists > 
"processes" --> "*" "files" : attachments > 
"processes" --> "*" "ipdc-products" : ipdc-products > 
"processes" --> "*" "administrative-unit-classification-codes" : relevant-administrative-units > 
"processes" --> "*" "information-assets" : information-assets > 
"processes" --> "*" "processes" : linked-blueprints > 
"processes" --> "*" "groups" : users > 
"processes" --> "*" "links" : links > 
class "boundary-events"
"boundary-events" : reference
"boundary-events" : outgoing
"boundary-events" : eventdefinition
"bpmn-elements" <|-- "boundary-events"
class "sub-processes"
"sub-processes" : ramilayer
"sub-processes" : view
"bpmn-elements" <|-- "sub-processes"
class "jobs"
"jobs" : status
"jobs" : created
"jobs" : modified
"jobs" : resource
"jobs" : operation
"jobs" --> "1" "groups" : creator > 
class "error-event-defintions"
"bpmn-elements" <|-- "error-event-defintions"
class "user-tasks"
"tasks" <|-- "user-tasks"
class "files"
"files" : name
"files" : format
"files" : size
"files" : extension
"files" : version
"files" : created
"files" : modified
"files" : status
"files" --> "1" "files" : download > 
"files" --> "*" "information-assets" : information-assets > 
class "bpmn-processes"
"bpmn-processes" --> "1" "files" : bpmn-file > 
class "data-objects"
"bpmn-elements" <|-- "data-objects"
class "lane-sets"
"bpmn-elements" <|-- "lane-sets"
class "send-tasks"
"tasks" <|-- "send-tasks"
class "information-assets"
"information-assets" : title
"information-assets" : description
"information-assets" : created
"information-assets" : modified
"information-assets" : status
"information-assets" : confidentiality-score
"information-assets" : integrity-score
"information-assets" : availability-score
"information-assets" : contains-personal-data
"information-assets" : contains-professional-data
"information-assets" : contains-sensitive-personal-data
"information-assets" --> "1" "groups" : creator > 
"information-assets" --> "*" "processes" : processes > 
"information-assets" --> "*" "files" : attachments > 
"information-assets" --> "*" "links" : links > 
"information-assets" --> "*" "versioned-information-assets" : versions > 
class "process-categories"
"process-categories" : label
"process-categories" : created
"process-categories" : modified
"process-categories" : status
"process-categories" : scheme
"process-categories" : archived-at
class "message-event-definitions"
"bpmn-elements" <|-- "message-event-definitions"
class "associations"
"associations" : source
"associations" : target
"bpmn-elements" <|-- "associations"
class "versioned-information-assets"
"versioned-information-assets" --> "1" "information-assets" : canonical > 
"versioned-information-assets" --> "1" "versioned-information-assets" : previous-version > 
"information-assets" <|-- "versioned-information-assets"
class "versioned-processes"
"versioned-processes" --> "1" "processes" : canonical > 
"versioned-processes" --> "1" "versioned-processes" : previous-version > 
"processes" <|-- "versioned-processes"
class "properties"
"properties" : propertyelement
"bpmn-elements" <|-- "properties"
class "intermediate-throw-events"
"intermediate-throw-events" : eventdefinition
"intermediate-throw-events" : outgoing
"intermediate-throw-events" : incoming
"bpmn-elements" <|-- "intermediate-throw-events"
class "ipdc-instances"
"ipdc-products" <|-- "ipdc-instances"
class "process-domains"
"process-domains" : label
"process-domains" : created
"process-domains" : modified
"process-domains" : status
"process-domains" : scheme
"process-domains" : archived-at
"process-domains" --> "*" "process-categories" : process-categories > 
class "sequence-flows"
"sequence-flows" : source
"sequence-flows" : target
"bpmn-elements" <|-- "sequence-flows"
class "links"
"links" : label
"links" : href
"links" : created
"links" : modified
"links" : status
"links" --> "*" "information-assets" : information-assets > 
"links" --> "*" "processes" : process > 
class "lanes"
"lanes" : activity
"bpmn-elements" <|-- "lanes"
class "diagram-lists"
"diagram-lists" : order
"diagram-lists" : version
"diagram-lists" : created
"diagram-lists" : modified
"diagram-lists" : status
"diagram-lists" --> "*" "diagram-list-items" : diagrams > 
class "diagram-list-items"
"diagram-list-items" : position
"diagram-list-items" : created
"diagram-list-items" : modified
"diagram-list-items" : status
"diagram-list-items" --> "1" "files" : diagram-file > 
"diagram-list-items" --> "*" "diagram-list-items" : sub-items > 
class "reports"
"reports" : title
"reports" : description
"reports" : created
"reports" --> "1" "files" : file > 
class "ipdc-concepts"
"ipdc-products" <|-- "ipdc-concepts"
class "bpmn-elements"
"bpmn-elements" : name
"bpmn-elements" --> "1" "bpmn-element-types" : type > 
"bpmn-elements" --> "1" "bpmn-processes" : bpmn-process > 
class "manual-tasks"
"tasks" <|-- "manual-tasks"
class "data-output-associations"
"data-output-associations" : target
"data-output-associations" : dataoutputfrom
"bpmn-elements" <|-- "data-output-associations"
class "script-tasks"
"tasks" <|-- "script-tasks"
class "groups"
"groups" : name
"groups" : identifier
"groups" --> "1" "administrative-unit-classification-codes" : classification > 
"groups" --> "1" "sites" : primary-site > 
"groups" --> "*" "processes" : processes > 
class "data-store-references"
"bpmn-elements" <|-- "data-store-references"
@enduml
