(in-package :mu-cl-resources)

(define-resource conceptualProcess ()
  :class (s-prefix "oph:ConceptueelProces")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:number :number ,(s-prefix "dct:identifier"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status")))
  :has-many `((processGroup :via ,(s-prefix "oph:procesGroep")
                             :as "process-groups"))
  :resource-base (s-url "http://data.lblod.info/conceptual-processes/")
  :on-path "conceptual-processes")

(define-resource processGroup ()
  :class (s-prefix "skos:Concept")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:scheme :url ,(s-prefix "skos:inScheme")))
  :has-many `((processDomain :via ,(s-prefix "skos:relatedMatch")
                             :as "process-domains"))
  :resource-base (s-url "http://data.lblod.info/process-groups/")
  :on-path "process-groups")

(define-resource processDomain ()
  :class (s-prefix "skos:Concept")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:scheme :url ,(s-prefix "skos:inScheme")))
  :has-many `((processCategory :via ,(s-prefix "skos:relatedMatch")
                               :as "process-categories"))
  :resource-base (s-url "http://data.lblod.info/process-domains/")
  :on-path "process-domains")

(define-resource processCategory ()
  :class (s-prefix "skos:Concept")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:scheme :url ,(s-prefix "skos:inScheme")))
  :resource-base (s-url "http://data.lblod.info/process-categories/")
  :on-path "process-categories")