(in-package :mu-cl-resources)

(define-resource informationAsset()
  :class (s-prefix "icr:InformationAsset")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:confidentiality-score :number ,(s-prefix "icr:confidentialityScore"))
                (:integrity-score :number ,(s-prefix "icr:integrityScore"))
                (:availability-score :number ,(s-prefix "icr:availabilityScore"))
                (:contains-personal-data :boolean ,(s-prefix "icr:containsPersonalData"))
                (:contains-professional-data :boolean ,(s-prefix "icr:containsProfessionalData"))
                (:contains-sensitive-personal-data :boolean ,(s-prefix "icr:containsSensitivePersonalData")))
  :has-one `((group :via ,(s-prefix "dct:creator")
                    :as "creator"))
  :has-many `((process :via ,(s-prefix "icr:hasInformationAsset")
                       :inverse t
                       :as "processes")
              (file :via ,(s-prefix "schema:associatedMedia")
                    :as "attachments")
              (link :via ,(s-prefix "rdfs:seeAlso")
                    :as "links")
              (versionedInformationAsset :via ,(s-prefix "dct:isVersionOf")
                                         :inverse t
                                         :as "versions"))
  :resource-base (s-url "http://data.lblod.info/information-assets/")
  :on-path "information-assets")

(define-resource versionedInformationAsset(informationAsset)
  :class (s-prefix "ext:VersionedInformationAsset")
  :has-one `((informationAsset :via ,(s-prefix "dct:isVersionOf")
                               :as "canonical")
             (versionedInformationAsset :via ,(s-prefix "prov:wasRevisionOf")
                                        :as "previous-version"))
  :resource-base (s-url "http://data.lblod.info/information-assets/versions/")
  :on-path "versioned-information-assets")
