(in-package :mu-cl-resources)

(define-resource process()
  :class (s-prefix "dpv:Process")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:email :string ,(s-prefix "schema:email"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:confidentiality-score :number ,(s-prefix "icr:confidentialityScore"))
                (:integrity-score :number ,(s-prefix "icr:integrityScore"))
                (:availability-score :number ,(s-prefix "icr:availabilityScore"))
                (:contains-personal-data :boolean ,(s-prefix "icr:containsPersonalData"))
                (:contains-professional-data :boolean ,(s-prefix "icr:containsProfessionalData"))
                (:contains-sensitive-personal-data :boolean ,(s-prefix "icr:containsSensitivePersonalData"))
                (:additional-information :string ,(s-prefix "icr:additionalInformation"))
                (:has-control-measure :url ,(s-prefix "icr:hasControlMeasure"))
                (:is-blueprint :boolean ,(s-prefix "icr:isBlueprint")))
  :has-one `((group :via ,(s-prefix "dct:publisher")
                    :as "publisher")
             (processStatistic :via ,(s-prefix "ext:hasStatistics")
                               :as "process-statistics")
             (conceptualProcess :via ,(s-prefix "dct:source")
                               :as "linked-concept"))
  :has-many `((list :via ,(s-prefix "schema:hasPart")
                    :as "diagram-lists")
              (file :via ,(s-prefix "schema:associatedMedia")
                    :as "attachments")
              (ipdcProduct :via ,(s-prefix "cpsv:follows")
                           :inverse t
                           :as "ipdc-products")
              (administrative-unit-classification-codes :via ,(s-prefix "icr:isRelevantForAdministrativeUnit")
                                :as "relevant-administrative-units")
              (informationAsset :via ,(s-prefix "icr:hasInformationAsset")
                                :as "information-assets")
              (process :via ,(s-prefix "prov:wasInfluencedBy")
                       :as "linked-blueprints")
              (group :via ,(s-prefix "prov:usedBy")
                     :as "users")
              (link :via ,(s-prefix "rdfs:seeAlso")
                    :as "links"))
  :resource-base (s-url "http://data.lblod.info/processes/")
  :on-path "processes")

(define-resource list()
  :class (s-prefix "schema:ItemList")
  :properties `((:order :url ,(s-prefix "schema:itemListOrder"))
                (:version :string ,(s-prefix "schema:version"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-many `((listItem :via ,(s-prefix "schema:itemListElement")
                        :as "diagrams"))
  :resource-base (s-url "http://data.lblod.info/lists/")
  :on-path "lists")

(define-resource listItem()
  :class (s-prefix "schema:ListItem")
  :properties `((:position :number ,(s-prefix "schema:position"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-one `((file :via ,(s-prefix "schema:item")
                   :as "diagram-file"))
  :has-many `((listItem :via ,(s-prefix "schema:hasPart")
                        :as "sub-items"))
  :resource-base (s-url "http://data.lblod.info/list-items/")
  :on-path "list-items")

(define-resource informationAsset()
  :class (s-prefix "icr:InformationAsset")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:status :url ,(s-prefix "adms:status"))
                (:confidentiality-score :number ,(s-prefix "icr:confidentialityScore"))
                (:integrity-score :number ,(s-prefix "icr:integrityScore"))
                (:availability-score :number ,(s-prefix "icr:availabilityScore"))
                (:contains-personal-data :boolean ,(s-prefix "icr:containsPersonalData"))
                (:contains-professional-data :boolean ,(s-prefix "icr:containsProfessionalData"))
                (:contains-sensitive-personal-data :boolean ,(s-prefix "icr:containsSensitivePersonalData")))
  :has-one `((informationAsset :via ,(s-prefix "prov:wasRevisionOf")
                               :as "previous-version")
            (group :via ,(s-prefix "dct:creator")
                   :as "creator"))
  :has-many `((process :via ,(s-prefix "icr:hasInformationAsset")
                       :inverse t
                       :as "processes"))
  :resource-base (s-url "http://data.lblod.info/information-assets/")
  :on-path "information-assets")

  (define-resource link ()
  :class (s-prefix "nfo:Bookmark")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:href :string ,(s-prefix "nie:links")))
  :has-one `((process :via ,(s-prefix "rdfs:seeAlso")
                      :inverse t
                      :as "process"))
  :resource-base (s-url "http://data.lblod.info/links/")
  :on-path "links")
