(in-package :mu-cl-resources)

(define-resource process()
  :class (s-prefix "dpv:Process")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:email :string ,(s-prefix "schema:email"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:is-blueprint :boolean ,(s-prefix "icr:isBlueprint"))
                (:additional-information :string ,(s-prefix "icr:additionalInformation"))
                (:has-control-measure :url ,(s-prefix "icr:hasControlMeasure")))
  :has-one `((group :via ,(s-prefix "dct:publisher")
                    :as "publisher")
             (group :via ,(s-prefix "dct:creator")
                    :as "creator")
             (processStatistic :via ,(s-prefix "ext:hasStatistics")
                               :as "process-statistics")
             (conceptualProcess :via ,(s-prefix "dct:source")
                               :as "linked-concept"))
  :has-many `((diagram-list :via ,(s-prefix "schema:hasPart")
                    :as "diagram-lists")
              (file :via ,(s-prefix "schema:associatedMedia")
                    :as "attachments")
              (ipdcProduct :via ,(s-prefix "cpsv:follows")
                           :inverse t
                           :as "ipdc-products")
              (administrative-unit-classification-codes :via ,(s-prefix "icr:isRelevantForAdministrativeUnit")
                                :as "relevant-administrative-units")
              (informationAsset :via ,(s-prefix "icr:hasInformationAsset")
                                :as "information-assets")
              (process :via ,(s-prefix "prov:wasInfluencedBy")
                       :as "linked-blueprints")
              (group :via ,(s-prefix "prov:usedBy")
                     :as "users")
              (link :via ,(s-prefix "rdfs:seeAlso")
                    :as "links"))
  :resource-base (s-url "http://data.lblod.info/processes/")
  :on-path "processes")

(define-resource versionedProcess(process)
  :class (s-prefix "ext:VersionedProcess")
  :has-one `((process :via, (s-prefix "dct:isVersionOf")
                      :as canonical)
             (versionedProcess :via ,(s-prefix "prov:wasRevisionOf")
                               :as "previous-version"))
  :resource-base (s-url "http://data.lblod.info/processes/versions/")
  :on-path "versioned-processes")

(define-resource diagram-list()
  :class (s-prefix "schema:ItemList")
  :properties `((:order :url ,(s-prefix "schema:itemListOrder"))
                (:version :string ,(s-prefix "schema:version"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-many `((diagram-list-item :via ,(s-prefix "schema:itemListElement")
                        :as "diagrams"))
  :resource-base (s-url "http://data.lblod.info/diagram-lists/")
  :on-path "diagram-lists")

(define-resource diagram-list-item()
  :class (s-prefix "schema:ListItem")
  :properties `((:position :number ,(s-prefix "schema:position"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-one `((file :via ,(s-prefix "schema:item")
                   :as "diagram-file"))
  :has-many `((diagram-list-item :via ,(s-prefix "schema:hasPart")
                        :as "sub-items"))
  :resource-base (s-url "http://data.lblod.info/diagram-list-items/")
  :on-path "diagram-list-items")

(define-resource link ()
  :class (s-prefix "nfo:Bookmark")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:href :string ,(s-prefix "nie:links")))
  :has-one `((process :via ,(s-prefix "rdfs:seeAlso")
                      :inverse t
                      :as "process"))
  :has-many `(
            (informationAsset :via ,(s-prefix "rdfs:seeAlso")
                            :inverse t
                            :as "information-assets"))
  :resource-base (s-url "http://data.lblod.info/links/")
  :on-path "links")
