PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>


CONSTRUCT {
  ?s ere:vestigingstype ?type .
} WHERE {
  ?s a org:Site ;
     rdf:type ?type ;
     mu:uuid ?uuid ;
     ere:vestigingstype ?type .
}
