PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>


CONSTRUCT {
  ?s org:siteAddress ?address .
} WHERE {
  ?s a org:Site ;
     mu:uuid ?uuid ;
     org:siteAddress ?address .
}
