PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?uri
      mu:uuid ?uuid ;
      rdf:type besluit:Bestuurseenheid ;
      skos:prefLabel ?name ;
      dct:identifier ?ovo ;
      dct:identifier ?kbo .
    ?organizationGraph ext:ownedBy ?uri .
  }
}
WHERE {
  VALUES (?uri ?uuid ?name ?ovo ?kbo) {
    (<http://data.lblod.info/id/bestuurseenheden/21b72711-c11c-43fb-9806-4c5e3c7fbd25> "21b72711-c11c-43fb-9806-4c5e3c7fbd25" "Agentschap Binnenlands Bestuur" "OVO001835" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/064f6d00-fb94-4e82-81f6-979f62309403> "064f6d00-fb94-4e82-81f6-979f62309403" "agentschap Digitaal Vlaanderen" "OVO002949" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/46d54a7b-f885-455b-afd1-68def1739d2f> "46d54a7b-f885-455b-afd1-68def1739d2f" "Agentschap Facilitair Bedrijf" "OVO001834" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7e24e42a-772d-43c4-b713-662a456396c2> "7e24e42a-772d-43c4-b713-662a456396c2" "Agentschap Integratie en Inburgering" "OVO001846" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/806c5b6a-a989-4ba4-9530-fb693896a05d> "806c5b6a-a989-4ba4-9530-fb693896a05d" "Agentschap Justitie en Handhaving" "OVO049152" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8b35b634-e1ca-4afb-95d5-4a5b9c3aaa9a> "8b35b634-e1ca-4afb-95d5-4a5b9c3aaa9a" "Agentschap Landbouw en Zeevisserij" "OVO000082" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2d636406-f8ff-4e69-8299-eb446460b431> "2d636406-f8ff-4e69-8299-eb446460b431" "Agentschap Overheidspersoneel" "OVO001833" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/e4361afb-c313-4bd5-8fe1-9cdee8b95f00> "e4361afb-c313-4bd5-8fe1-9cdee8b95f00" "Agentschap Plantentuin Meise" "OVO001523" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8009670b-c1d7-47a7-9eaa-3147e73eafa2> "8009670b-c1d7-47a7-9eaa-3147e73eafa2" "AGENTSCHAP VLAAMSE SOCIALE BESCHERMING" "OVO000120" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/24b72f90-4cf4-49ae-ae0f-db280a769983> "24b72f90-4cf4-49ae-ae0f-db280a769983" "Agentschap voor Hoger Onderwijs, Volwassenenonderwijs, Kwalificaties en Studietoelagen" "OVO001951" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/beb3eff1-d398-426b-89d8-5149d676734e> "beb3eff1-d398-426b-89d8-5149d676734e" "Agentschap voor Infrastructuur in het Onderwijs" "OVO000053" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/1b76dcbb-fbd7-4e5c-bcea-ae485bb28a17> "1b76dcbb-fbd7-4e5c-bcea-ae485bb28a17" "Agentschap voor Maritieme Dienstverlening en Kust" "OVO000097" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c183e48b-3349-48eb-9ac6-577ddcd21ddb> "c183e48b-3349-48eb-9ac6-577ddcd21ddb" "Agentschap voor Natuur en Bos" "OVO000089" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c6ea234d-efcd-449b-b107-71b209778023> "c6ea234d-efcd-449b-b107-71b209778023" "Agentschap voor Onderwijsdiensten" "OVO000050" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/e074d601-42dd-459d-8f0a-9241cbce49ef> "e074d601-42dd-459d-8f0a-9241cbce49ef" "Agentschap Wegen en Verkeer" "OVO000098" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/593c6a40-694d-4e22-b0f2-98f7483f4188> "593c6a40-694d-4e22-b0f2-98f7483f4188" "Annick De Ridder, Vlaams minister van Mobiliteit, Openbare Werken, Havens en Sport" "OVO054212" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/77f025e5-73b4-42a7-8534-4f76449381c2> "77f025e5-73b4-42a7-8534-4f76449381c2" "Atos - ICT-partner voor Cloud- en datacenterdiensten" "OVO048640" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/dd454b76-9f92-4ae6-9ba6-7617e5f8d432> "dd454b76-9f92-4ae6-9ba6-7617e5f8d432" "Atos - ICT-partner voor Service-integratiediensten" "OVO048641" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/60b73994-818d-4860-a5a1-f811428511ca> "60b73994-818d-4860-a5a1-f811428511ca" "Audit Vlaanderen" "OVO001832" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/82a15ff0-2eba-43fe-91aa-38b9bb2b7035> "82a15ff0-2eba-43fe-91aa-38b9bb2b7035" "Beheersmaatschappij Antwerpen Mobiel" "OVO000122" "860139085")
    (<http://data.lblod.info/id/bestuurseenheden/ca1c4692-5221-4590-8ab3-409ba1fa10bc> "ca1c4692-5221-4590-8ab3-409ba1fa10bc" "Ben Weyts, viceminister-president van de Vlaamse Regering en Vlaams minister van Begroting en Financiën, Vlaamse Rand, Onroerend Erfgoed en Dierenwelzijn" "OVO054207" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/47f8c1f9-6d2e-428d-a829-c2c0ef5c5b80> "47f8c1f9-6d2e-428d-a829-c2c0ef5c5b80" "Caroline Gennez, Vlaams minister van Welzijn en Armoedebestrijding, Cultuur en Gelijke Kansen" "OVO054210" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/17c6c8da-78ad-41f9-b944-f23c1b513b77> "17c6c8da-78ad-41f9-b944-f23c1b513b77" "Cegeka - ICT-partner voor Werkplekdiensten" "OVO048643" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/643c500f-f110-4b83-89e3-f07eec92afcf> "643c500f-f110-4b83-89e3-f07eec92afcf" "Cieltje Van Achter, Vlaams minister van Brussel en Media" "OVO054213" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b96edab3-fdea-4345-9005-d910b96bd420> "b96edab3-fdea-4345-9005-d910b96bd420" "Cronos Public Services - ICT-partner voor Applicatiediensten" "OVO048644" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/4e4fd946-ccfa-4f19-8ff2-45a7880ff1a5> "4e4fd946-ccfa-4f19-8ff2-45a7880ff1a5" "Cultuurconnect" "OVO003327" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d97e39cc-d5e5-489c-9100-6943613206c2> "d97e39cc-d5e5-489c-9100-6943613206c2" "De Ambrassade" "OVO004224" "475787275")
    (<http://data.lblod.info/id/bestuurseenheden/24e816a2-5486-45b7-8b18-f334295b0ad3> "24e816a2-5486-45b7-8b18-f334295b0ad3" "De Vlaamse Radio- en Televisieomroeporganisatie" "OVO000073" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3298819f-571e-4cc6-b6c7-43c92da140de> "3298819f-571e-4cc6-b6c7-43c92da140de" "DE VLAAMSE WATERWEG" "OVO000112" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/18f4bd84-6a63-4995-899f-397da1fcac54> "18f4bd84-6a63-4995-899f-397da1fcac54" "De Werkvennootschap" "OVO001559" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/940012ec-c6d9-4883-a32b-3ff65acd1c40> "940012ec-c6d9-4883-a32b-3ff65acd1c40" "Departement Cultuur, Jeugd en Media" "OVO000067" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3d984ed4-b9b7-4a78-b4e2-afe3209e741e> "3d984ed4-b9b7-4a78-b4e2-afe3209e741e" "Departement Financiën en Begroting" "OVO000029" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2cc26b3d-b9f9-4c2e-8b22-c60a683e04f3> "2cc26b3d-b9f9-4c2e-8b22-c60a683e04f3" "Departement Kanselarij en Buitenlandse Zaken" "OVO000032" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/04d83209-7023-4999-9929-ee76989bc7fb> "04d83209-7023-4999-9929-ee76989bc7fb" "Departement Mobiliteit en Openbare Werken" "OVO000096" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7d7b883a-86b3-4917-8fe8-a525b92e8026> "7d7b883a-86b3-4917-8fe8-a525b92e8026" "Departement Omgeving" "OVO003323" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/65a26cd5-65d8-4e72-b9bc-579123f97504> "65a26cd5-65d8-4e72-b9bc-579123f97504" "Departement Onderwijs en Vorming" "OVO000049" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/eef859ec-95fe-445e-b76f-b34e5e382501> "eef859ec-95fe-445e-b76f-b34e5e382501" "Departement Werk, Economie, Wetenschap, Innovatie en Sociale Economie" "OVO053580" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3f3a2be5-d6b3-441f-a2b2-a56c84c57a77> "3f3a2be5-d6b3-441f-a2b2-a56c84c57a77" "Departement Zorg" "OVO000056" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/46745211-6a72-4b4d-ae26-3e192497805f> "46745211-6a72-4b4d-ae26-3e192497805f" "Dienst met Afzonderlijk Beheer Loodswezen" "OVO000558" "767420151")
    (<http://data.lblod.info/id/bestuurseenheden/4299dcc8-e729-44f2-b439-765754a244bd> "4299dcc8-e729-44f2-b439-765754a244bd" "Dienst met Afzonderlijk Beheer Vloot" "OVO000559" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/cf7560ce-4472-49b5-8739-4762020e9618> "cf7560ce-4472-49b5-8739-4762020e9618" "Dienst van de Bestuursrechtscolleges" "OVO001831" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3902b206-c421-43ea-a900-ea79a954d640> "3902b206-c421-43ea-a900-ea79a954d640" "Dienst van de gouverneurs" "OVO001830" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/47d5f769-7524-44cc-8a7e-22d2f1abcb4f> "47d5f769-7524-44cc-8a7e-22d2f1abcb4f" "DXC Technology - ICT-partner voor mainframediensten" "OVO048649" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d8e4934b-b786-4470-8982-32b723b30637> "d8e4934b-b786-4470-8982-32b723b30637" "DXC-Cegeka - ICT-partner voor Applicatiediensten" "OVO048646" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/f3779ec8-bc0c-4c5c-808f-e2499f1fdae6> "f3779ec8-bc0c-4c5c-808f-e2499f1fdae6" "Eigen Vermogen \"Flanders Hydraulics" "OVO000223" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d974b670-9452-4c0c-8e73-d9d12922c0e6> "d974b670-9452-4c0c-8e73-d9d12922c0e6" "Eigen Vermogen Digitaal Vlaanderen" "OVO002956" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/00eaf903-88bf-4bf4-b075-750ac00beb12> "00eaf903-88bf-4bf4-b075-750ac00beb12" "Eigen Vermogen van het Instituut voor Natuur- en Bosonderzoek" "OVO000146" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d9623070-417b-474b-84b3-c4546e444145> "d9623070-417b-474b-84b3-c4546e444145" "EIGEN VERMOGEN VH INSTITUUT VOOR LANDBOUW- EN VISSERIJONDERZOEK" "OVO000147" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7d6d69ed-aa69-40b1-9b40-931eb1110581> "7d6d69ed-aa69-40b1-9b40-931eb1110581" "Eigen Vermogen Xperta" "OVO053646" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2b7a7bd6-0cb4-4305-8d57-daf449cd45ea> "2b7a7bd6-0cb4-4305-8d57-daf449cd45ea" "ESF - AGENTSCHAP VLAANDEREN" "OVO000080" "476731541")
    (<http://data.lblod.info/id/bestuurseenheden/d2872296-04ae-4426-afa4-1ddb695c19a4> "d2872296-04ae-4426-afa4-1ddb695c19a4" "Eviden - ICT-partner voor Applicatiediensten" "OVO048639" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/39e2afc7-2ea8-467a-b98f-2da42f3aae12> "39e2afc7-2ea8-467a-b98f-2da42f3aae12" "Financieringsinstrument voor de Vlaamse visserij- en aquacultuursector" "OVO000150" "265527701")
    (<http://data.lblod.info/id/bestuurseenheden/93b29e6c-3477-4281-8df9-2e7a93ad89b9> "93b29e6c-3477-4281-8df9-2e7a93ad89b9" "Fonds voor Innoveren en Ondernemen" "OVO000140" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7a707e65-cabb-416c-8a98-fe69a649dd35> "7a707e65-cabb-416c-8a98-fe69a649dd35" "Fonds voor wetenschappelijk Onderzoek - Vlaanderen" "OVO000042" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/dd11d1d1-2401-4bb3-b2c8-660adbca34f0> "dd11d1d1-2401-4bb3-b2c8-660adbca34f0" "Gouverneur van de provincie Limburg" "OVO027526" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/fefe37be-293e-4015-87df-72276e2e5d3f> "fefe37be-293e-4015-87df-72276e2e5d3f" "Gouverneur van de provincie Oost-Vlaanderen" "OVO027528" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7a2f747a-70f5-4bef-82f5-2818dc975d50> "7a2f747a-70f5-4bef-82f5-2818dc975d50" "Grindfonds - Fonds gravier" "OVO000152" "250937416")
    (<http://data.lblod.info/id/bestuurseenheden/a7c5b9cc-fc34-4e15-83f2-a23bc153e791> "a7c5b9cc-fc34-4e15-83f2-a23bc153e791" "Handhavingscollege" "OVO001689" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3dcdd756-2a16-4ea4-a1fb-f819c7130577> "3dcdd756-2a16-4ea4-a1fb-f819c7130577" "Hans Bonte, viceminister-president van de Vlaamse Regering en Vlaams minister van Wonen, Energie en Klimaat, Toerisme en Jeugd" "OVO056605" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b07ea84d-5d8f-469b-a4d1-8f2977d1ffc3> "b07ea84d-5d8f-469b-a4d1-8f2977d1ffc3" "het Gemeenschapsonderwijs" "OVO000109" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/88107e7a-58f4-47bc-95ef-ed35fb7e2bd3> "88107e7a-58f4-47bc-95ef-ed35fb7e2bd3" "Het Kinderrechtencommissariaat" "OVO000795" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/ce7ab802-cfa3-40eb-9399-0f7fe18a3aff> "ce7ab802-cfa3-40eb-9399-0f7fe18a3aff" "Het Vlaams Parlement" "OVO000617" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/018011fd-9c3e-4544-b7f7-ff4952eb0d7b> "018011fd-9c3e-4544-b7f7-ff4952eb0d7b" "Hilde Crevits, viceminister-president van de Vlaamse Regering en Vlaams minister van Binnenland, Steden- en Plattelandsbeleid, Samenleven, Integratie en Inburgering, Bestuurszaken, Sociale Economie en Zeevisserij" "OVO054206" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8bb52ed4-863c-4044-8be7-ddc59dfe7096> "8bb52ed4-863c-4044-8be7-ddc59dfe7096" "Inspectie van Financiën" "OVO000832" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/81cac073-545d-46ce-90ad-455948e8cc69> "81cac073-545d-46ce-90ad-455948e8cc69" "Instituut voor Landbouw-, Visserij- en Voedingsonderzoek" "OVO000084" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/582749e9-2da0-4565-8130-c3b76978820f> "582749e9-2da0-4565-8130-c3b76978820f" "Instituut voor Natuur- en Bosonderzoek" "OVO000088" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2c12347f-8e55-4e76-96eb-e3c3685a7e18> "2c12347f-8e55-4e76-96eb-e3c3685a7e18" "Intercommunale Maatschappij Opera voor Vlaanderen" "OVO008456" "222061110")
    (<http://data.lblod.info/id/bestuurseenheden/2cece35b-d8db-4586-9d38-7bd3b4a96ac8> "2cece35b-d8db-4586-9d38-7bd3b4a96ac8" "Interregionale entiteit VIAPASS" "OVO002333" "558940031")
    (<http://data.lblod.info/id/bestuurseenheden/1fe215ee-c3ac-4853-881a-e1ac73e5b924> "1fe215ee-c3ac-4853-881a-e1ac73e5b924" "Jo Brouns, Vlaams minister van Omgeving en Landbouw" "OVO054209" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/562da012-ad8a-4dab-b295-a7b556e433a7> "562da012-ad8a-4dab-b295-a7b556e433a7" "Kabinet van de minister-president van de Vlaamse Regering, Vlaams minister van Economie, Innovatie en Industrie, Buitenlandse Zaken, Digitalisering en Facilitair Management" "OVO053549" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b353498b-5189-4837-b2a1-ffb990efa131> "b353498b-5189-4837-b2a1-ffb990efa131" "Kabinet van de viceminister-president van de Vlaamse Regering, Vlaams minister van Begroting en Financiën, Vlaamse Rand, Onroerend Erfgoed en Dierenwelzijn" "OVO053551" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/eb37e38c-e94b-45f5-9b59-7b151175415f> "eb37e38c-e94b-45f5-9b59-7b151175415f" "Kabinet van de viceminister-president van de Vlaamse Regering, Vlaams minister van Binnenland, Steden- en Plattelandsbeleid, Samenleven, Integratie en Inburgering, Bestuurszaken, Sociale Economie en Zeevisserij" "OVO053550" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/210b2f38-78df-401a-837a-0a72cc3fe208> "210b2f38-78df-401a-837a-0a72cc3fe208" "Kabinet van de viceminister-president van de Vlaamse Regering, Vlaams minister van Wonen, Energie en Klimaat, Toerisme en Jeugd" "OVO053552" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/582da3eb-535e-48c7-a0bf-7c6ce12cbb91> "582da3eb-535e-48c7-a0bf-7c6ce12cbb91" "Kabinet van de Vlaamse minister van Brussel en Media" "OVO053557" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d928bb68-2adf-4b02-a729-078d129d00b5> "d928bb68-2adf-4b02-a729-078d129d00b5" "Kabinet van de Vlaamse minister van Mobiliteit, Openbare Werken, Havens en Sport" "OVO053556" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/fb809dfd-62a3-487d-95b9-61d00fabd237> "fb809dfd-62a3-487d-95b9-61d00fabd237" "Kabinet van de Vlaamse minister van Omgeving en Landbouw" "OVO053553" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b47a2472-1ae6-418f-9732-ad891d3c3900> "b47a2472-1ae6-418f-9732-ad891d3c3900" "Kabinet van de Vlaamse minister van Onderwijs, Justitie en Werk" "OVO053555" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/a3455b90-35a4-4c0d-bd41-037bfc57c415> "a3455b90-35a4-4c0d-bd41-037bfc57c415" "Kabinet van de Vlaamse minister van Welzijn en Armoedebestrijding, Cultuur en Gelijke Kansen" "OVO053554" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/f0129800-b4ab-4b1d-9865-66245e33dd7f> "f0129800-b4ab-4b1d-9865-66245e33dd7f" "Koninklijk Museum voor Schone Kunsten Antwerpen" "OVO001651" "725891877")
    (<http://data.lblod.info/id/bestuurseenheden/c0d3b3ce-71a5-4ff3-aead-6a0cdc93bdcf> "c0d3b3ce-71a5-4ff3-aead-6a0cdc93bdcf" "Koninklijke Academie voor Nederlandse Taal en Letteren" "OVO000184" "210012621")
    (<http://data.lblod.info/id/bestuurseenheden/31f68522-961b-4bbc-aba4-b35b79e5883d> "31f68522-961b-4bbc-aba4-b35b79e5883d" "KONINKLIJKE VLAAMSE ACADEMIE VAN BELGIE VOOR WETENSCHAPPEN & KUNSTEN" "OVO000182" "852088679")
    (<http://data.lblod.info/id/bestuurseenheden/f274f07f-37f2-481e-b5a4-7e24142e88e0> "f274f07f-37f2-481e-b5a4-7e24142e88e0" "LIMBURGSE RECONVERSIE MAATSCHAPPIJ" "OVO000043" "452138972")
    (<http://data.lblod.info/id/bestuurseenheden/852e7bfb-4775-4174-a9cd-f2378874d797> "852e7bfb-4775-4174-a9cd-f2378874d797" "Literatuur Vlaanderen" "OVO000174" "850465910")
    (<http://data.lblod.info/id/bestuurseenheden/d1abc3c2-330b-4662-8b12-27c8e34cde9e> "d1abc3c2-330b-4662-8b12-27c8e34cde9e" "LUCHTHAVENONTWIKKELINGSMAATSCHAPPIJ VLAANDEREN" "OVO001601" "553678968")
    (<http://data.lblod.info/id/bestuurseenheden/6629332b-2b08-4d06-964c-08fadfcd5478> "6629332b-2b08-4d06-964c-08fadfcd5478" "Matthias Diependaele, minister-president van de Vlaamse Regering en Vlaams minister van Economie, Innovatie en Industrie, Buitenlandse Zaken, Digitalisering en Facilitair Management" "OVO054205" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/065a1fd1-9795-4302-96ab-6a47dda4a92c> "065a1fd1-9795-4302-96ab-6a47dda4a92c" "Melissa Depraetere, viceminister-president van de Vlaamse Regering en Vlaams minister van Wonen, Energie en Klimaat, Toerisme en Jeugd" "OVO054208" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3eeb5b87-08bf-4751-bcdd-e058f61b04ae> "3eeb5b87-08bf-4751-bcdd-e058f61b04ae" "Milieu- en Natuurraad van Vlaanderen" "OVO000095" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c69b4b59-b458-470c-aa0e-a7f9915d8734> "c69b4b59-b458-470c-aa0e-a7f9915d8734" "Mobiliteitsraad van Vlaanderen" "OVO000210" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/dee62f29-08bc-49ac-9681-c26c74454e56> "dee62f29-08bc-49ac-9681-c26c74454e56" "Muntpunt" "OVO001842" "838774539")
    (<http://data.lblod.info/id/bestuurseenheden/43e3d604-3221-42ee-9284-31e51b3ce3b8> "43e3d604-3221-42ee-9284-31e51b3ce3b8" "Natuurinvest" "OVO000145" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/9f823cdc-6f1e-4180-b7a6-04624fc8e78b> "9f823cdc-6f1e-4180-b7a6-04624fc8e78b" "Onderwijsinspectie" "OVO002410" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/54fda9b0-e45a-4e54-a5e1-45f8acfd8d82> "54fda9b0-e45a-4e54-a5e1-45f8acfd8d82" "Onroerend Erfgoed" "OVO000104" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/cbb10c49-27a4-4ba4-820a-78fff9826e58> "cbb10c49-27a4-4ba4-820a-78fff9826e58" "OPENBAAR PSYCHIATRISCH ZORGCENTRUM GEEL" "OVO000062" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/5ff09881-9d8f-4493-acd5-56634e25da7b> "5ff09881-9d8f-4493-acd5-56634e25da7b" "Openbaar Psychiatrisch Zorgcentrum Rekem" "OVO000063" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/5fc150c0-ed96-4848-8047-b72bf0654559> "5fc150c0-ed96-4848-8047-b72bf0654559" "Openbare Vlaamse Afvalstoffenmaatschappij" "OVO000091" "842399963")
    (<http://data.lblod.info/id/bestuurseenheden/af55f96c-e8c8-418e-a927-025c0f0bc272> "af55f96c-e8c8-418e-a927-025c0f0bc272" "Opgroeien" "OVO000058" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2953ff6d-4f05-43f0-8d36-335aebaaff85> "2953ff6d-4f05-43f0-8d36-335aebaaff85" "Opgroeien regie" "OVO000061" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/9de01054-4405-472c-88db-450ec7c4a768> "9de01054-4405-472c-88db-450ec7c4a768" "Participatiemaatschappij Vlaanderen" "OVO000044" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/72b074e6-b9ab-4efc-a87e-d7c4f75f3c71> "72b074e6-b9ab-4efc-a87e-d7c4f75f3c71" "Pendelfonds" "OVO000193" "548967936")
    (<http://data.lblod.info/id/bestuurseenheden/cb0e49db-7305-42b8-9580-a26634026f7d> "cb0e49db-7305-42b8-9580-a26634026f7d" "Proximus - ICT-partner voor Netwerkdiensten" "OVO048642" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/eb4e45d6-16bd-4aac-81f5-6555905bd257> "eb4e45d6-16bd-4aac-81f5-6555905bd257" "Raad voor betwistingen inzake studievoortgangsbeslissingen" "OVO000857" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8f014af8-b3fe-4886-b10f-567262addb1b> "8f014af8-b3fe-4886-b10f-567262addb1b" "Raad voor Vergunningsbetwistingen" "OVO001688" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/18a9a64f-03d3-4aaa-ae05-91f0a280c2f1> "18a9a64f-03d3-4aaa-ae05-91f0a280c2f1" "Raad voor Verkiezingsbetwistingen" "OVO001680" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2c21e32f-90ad-4eb1-b82f-c9c34bcb2368> "2c21e32f-90ad-4eb1-b82f-c9c34bcb2368" "SCHOOL INVEST" "OVO001561" "810538136")
    (<http://data.lblod.info/id/bestuurseenheden/79df4823-49f2-40e7-9fe0-c753f231a83d> "79df4823-49f2-40e7-9fe0-c753f231a83d" "Sectoraal partnerschap autosector en aanverwante sectoren" "OVO003924" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b009cc52-d1bf-4271-ad58-efb66aa4a7fc> "b009cc52-d1bf-4271-ad58-efb66aa4a7fc" "Sectoraal Partnerschap Bedienden" "OVO051569" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/07c92480-aa77-4c4a-8bce-f84b5fcc26a9> "07c92480-aa77-4c4a-8bce-f84b5fcc26a9" "Sectoraal partnerschap binnenvaart" "OVO039309" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/7444b0f8-494a-4790-b468-c893a8bbee5f> "7444b0f8-494a-4790-b468-c893a8bbee5f" "Sectoraal partnerschap bouw" "OVO003925" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/41c8afde-cb7e-405d-8d74-a7cc0b418509> "41c8afde-cb7e-405d-8d74-a7cc0b418509" "Sectoraal partnerschap chemie, kunststoffen en life sciences" "OVO003926" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/60eef31e-6e96-48b7-8ff8-c058fc8e2f1e> "60eef31e-6e96-48b7-8ff8-c058fc8e2f1e" "Sectoraal partnerschap elektriciens : installatie en distributie" "OVO003927" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/50fc8a83-3300-43f9-8ea1-34a5f7045770> "50fc8a83-3300-43f9-8ea1-34a5f7045770" "Sectoraal partnerschap grafische sector en papier- en kartonbewerkende sector" "OVO047590" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c9b6b1af-5596-421b-9bf9-594e9dcb7db2> "c9b6b1af-5596-421b-9bf9-594e9dcb7db2" "Sectoraal partnerschap groene sectoren" "OVO003928" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/1c0bbd4d-14f7-4a7d-a477-528d2b29cfd7> "1c0bbd4d-14f7-4a7d-a477-528d2b29cfd7" "Sectoraal partnerschap Handel – Detailhandel" "OVO048566" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/5723e2e0-4af9-41cc-b980-46f07543e94a> "5723e2e0-4af9-41cc-b980-46f07543e94a" "Sectoraal partnerschap Handel – Voedingshandel" "OVO048565" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/ce29f3c7-bec9-4a8a-b9df-ab659015f252> "ce29f3c7-bec9-4a8a-b9df-ab659015f252" "Sectoraal Partnerschap Handel – Zelfstandige kleinhandel" "OVO048567" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d54e8de6-252e-4820-a508-ae3f4920ffb1> "d54e8de6-252e-4820-a508-ae3f4920ffb1" "Sectoraal partnerschap horeca" "OVO003930" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/eb38a44e-211a-4e91-b8d1-bbddaaa613f2> "eb38a44e-211a-4e91-b8d1-bbddaaa613f2" "Sectoraal partnerschap houtsectoren" "OVO003931" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/0666cdf5-a479-443f-8d95-503e6e199cc5> "0666cdf5-a479-443f-8d95-503e6e199cc5" "Sectoraal partnerschap kappers - fitness - schoonheidszorgen" "OVO003929" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c935ac2f-7bf5-4e13-9b81-007ca32d546c> "c935ac2f-7bf5-4e13-9b81-007ca32d546c" "Sectoraal partnerschap kleding en confectie" "OVO003937" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/513e51eb-689b-4cb6-b804-068d696d17de> "513e51eb-689b-4cb6-b804-068d696d17de" "Sectoraal partnerschap lokale besturen" "OVO003935" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/a7b2de38-b376-4edc-ad90-a9cda47357f4> "a7b2de38-b376-4edc-ad90-a9cda47357f4" "Sectoraal partnerschap social profit" "OVO003932" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/6af536f8-f827-41c7-809f-c07a0bdf79e0> "6af536f8-f827-41c7-809f-c07a0bdf79e0" "Sectoraal partnerschap technologische industrie" "OVO003938" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2869d6ca-46d1-44a3-957e-030ed5ee5c1d> "2869d6ca-46d1-44a3-957e-030ed5ee5c1d" "Sectoraal partnerschap textiel" "OVO003939" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/9000815d-1521-4281-aa1a-556fef6afd5b> "9000815d-1521-4281-aa1a-556fef6afd5b" "Sectoraal partnerschap textielverzorging" "OVO003933" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/e6bd3034-44fb-4252-8a76-f70b6b2123c4> "e6bd3034-44fb-4252-8a76-f70b6b2123c4" "Sectoraal partnerschap transport, logistiek en grondafhandeling op luchthavens" "OVO003936" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/21112264-2e64-4fcf-aaf7-ceceaed3b8d6> "21112264-2e64-4fcf-aaf7-ceceaed3b8d6" "Sectoraal partnerschap verkoop en marketing" "OVO003955" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/6e25d111-f7a5-43da-9779-5e72e60df09d> "6e25d111-f7a5-43da-9779-5e72e60df09d" "Sectoraal partnerschap voedingsindustrie" "OVO003934" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/5f018924-899c-40bd-b339-15275cd18275> "5f018924-899c-40bd-b339-15275cd18275" "Selectiecommissie Besturen van de erkende kerk- of geloofsgemeenschappen van de erkende erediensten" "OVO056917" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/83711dc4-d7bb-418d-bffb-662a9a6eca9b> "83711dc4-d7bb-418d-bffb-662a9a6eca9b" "Selectiecommissie Gemeenten" "OVO028730" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/adfeffbb-adbe-4e15-9000-0ff4564766b2> "adfeffbb-adbe-4e15-9000-0ff4564766b2" "Selectiecommissie Instellingen met een publieke taak" "OVO056916" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/ad6c35bd-2958-445c-b4e7-5798464610f2> "ad6c35bd-2958-445c-b4e7-5798464610f2" "Selectiecommissie Polders en Wateringen" "OVO056915" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d4b24d2f-e962-4166-b2ec-75e0c04aa59c> "d4b24d2f-e962-4166-b2ec-75e0c04aa59c" "Selectiecommissie Provincies" "OVO028731" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/883b9b9e-c310-4d01-a80b-18e34e760ed1> "883b9b9e-c310-4d01-a80b-18e34e760ed1" "Selectiecommissie Vlaamse overheid" "OVO028729" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/c32ed8f0-3faf-4a72-ae2e-9c648e19cb36> "c32ed8f0-3faf-4a72-ae2e-9c648e19cb36" "Sociaal Economische Raad van Vlaanderen" "OVO001847" "216754913")
    (<http://data.lblod.info/id/bestuurseenheden/9fd73d99-9b35-4bbc-84bf-66201b708093> "9fd73d99-9b35-4bbc-84bf-66201b708093" "SPORT VLAANDEREN" "OVO000070" "248142826")
    (<http://data.lblod.info/id/bestuurseenheden/7438350a-43f9-4803-a966-1859728409a9> "7438350a-43f9-4803-a966-1859728409a9" "STRATEGISCHE ADVIESRAAD RUIMTELIJKE ORDENING - ONROEREND ERFGOED" "OVO000107" "896717587")
    (<http://data.lblod.info/id/bestuurseenheden/b46292fb-3397-48dd-a772-51db5c468019> "b46292fb-3397-48dd-a772-51db5c468019" "Strategische Adviesraad voor Landbouw en Visserij" "OVO000086" "809759364")
    (<http://data.lblod.info/id/bestuurseenheden/e9cb2d68-ad69-4910-833c-7759d8b6e2d0> "e9cb2d68-ad69-4910-833c-7759d8b6e2d0" "TECHNOPOLIS" "OVO001565" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b818da99-92b5-4ed2-98ef-b74a3266fd5d> "b818da99-92b5-4ed2-98ef-b74a3266fd5d" "Toegankelijk Vlaanderen" "OVO001843" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/5d455a8c-8274-4cdf-a526-fd2d82556f05> "5d455a8c-8274-4cdf-a526-fd2d82556f05" "Toerisme Vlaanderen" "OVO000034" "225944375")
    (<http://data.lblod.info/id/bestuurseenheden/a1985ede-9bf9-4702-aecb-8aa95ff491c4> "a1985ede-9bf9-4702-aecb-8aa95ff491c4" "Topstukkenfonds" "OVO000166" "841642076")
    (<http://data.lblod.info/id/bestuurseenheden/4d8e645d-a002-4ee8-9779-96d1853ebd83> "4d8e645d-a002-4ee8-9779-96d1853ebd83" "Vlaams Agentschap voor de Uitbetaling van Toelagen in het kader van het Gezinsbeleid" "OVO008643" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/1938f0b8-8cbb-43a0-a770-031edc1fbb10> "1938f0b8-8cbb-43a0-a770-031edc1fbb10" "Vlaams Agentschap voor Internationaal Ondernemen" "OVO000035" "242401911")
    (<http://data.lblod.info/id/bestuurseenheden/c715ca8b-22f8-4ab0-a130-daa30c4d3264> "c715ca8b-22f8-4ab0-a130-daa30c4d3264" "VLAAMS AGENTSCHAP VOOR PERSONEN MET EEN HANDICAP" "OVO000060" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/fd203f35-e946-4750-a95b-35e0e4a87cc8> "fd203f35-e946-4750-a95b-35e0e4a87cc8" "Vlaams Agentschap voor Samenwerking rond Gegevensdeling tussen de Actoren in de Zorg" "OVO002411" "652816235")
    (<http://data.lblod.info/id/bestuurseenheden/2e274736-7040-4c9b-875e-abddb00976ed> "2e274736-7040-4c9b-875e-abddb00976ed" "VLAAMS AUDIOVISUEEL FONDS" "OVO000175" "475795886")
    (<http://data.lblod.info/id/bestuurseenheden/a22b73be-c1d1-4151-8108-8b72b6422679> "a22b73be-c1d1-4151-8108-8b72b6422679" "Vlaams Centrum voor Agro- en Visserijmarketing" "OVO000474" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/b39d6f58-7772-4fd6-a1f1-11ed63b30e16> "b39d6f58-7772-4fd6-a1f1-11ed63b30e16" "Vlaams Datanutsbedrijf" "OVO051320" "795547478")
    (<http://data.lblod.info/id/bestuurseenheden/100364da-8419-443b-a38f-05fd1a30529b> "100364da-8419-443b-a38f-05fd1a30529b" "Vlaams Energie- en Klimaatagentschap" "OVO000090" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/9e67da60-e8b3-42cc-8306-fba7adfc32bd> "9e67da60-e8b3-42cc-8306-fba7adfc32bd" "Vlaams Energiebedrijf" "OVO000733" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8d33fce8-84a4-481b-965b-851081f204a0> "8d33fce8-84a4-481b-965b-851081f204a0" "VLAAMS FONDS VOOR DE LASTENDELGING" "OVO000143" "265528095")
    (<http://data.lblod.info/id/bestuurseenheden/dc8724e9-05a5-44c8-94e6-9b5eaf7797b9> "dc8724e9-05a5-44c8-94e6-9b5eaf7797b9" "Vlaams Infocentrum Land- en Tuinbouw" "OVO000148" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/2ecb8a46-8997-4412-aa3a-972f2beb9c55> "2ecb8a46-8997-4412-aa3a-972f2beb9c55" "Vlaams Infrastructuurfonds voor Persoonsgebonden Aangelegenheden" "OVO000066" "254481973")
    (<http://data.lblod.info/id/bestuurseenheden/c71b879f-e849-477a-b45d-1a38b99486a9> "c71b879f-e849-477a-b45d-1a38b99486a9" "VLAAMS INSTITUUT VOOR DE ZEE" "OVO000236" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/a1301b1a-61b2-4f6c-9971-39cfa421326f> "a1301b1a-61b2-4f6c-9971-39cfa421326f" "Vlaams Instituut voor Vrede en Geweldpreventie" "OVO000798" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/bdffb035-7998-4626-ac0e-c43502239022> "bdffb035-7998-4626-ac0e-c43502239022" "Vlaams Landbouwinvesteringsfonds" "OVO000149" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/0b2d9b9c-37b6-4c9d-9df9-98c7958db62a> "0b2d9b9c-37b6-4c9d-9df9-98c7958db62a" "Vlaams Mensenrechteninstituut" "OVO050766" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/d278898c-4774-4feb-9cec-a1d6ecee57bb> "d278898c-4774-4feb-9cec-a1d6ecee57bb" "VLAAMS PENSIOENFONDS" "OVO027160" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/bb568ed7-2b17-43f4-a089-d8f2d2a8418d> "bb568ed7-2b17-43f4-a089-d8f2d2a8418d" "Vlaams Woningfonds" "OVO001729" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/60a11431-278f-4dd3-8f03-0b09f5340b58> "60a11431-278f-4dd3-8f03-0b09f5340b58" "Vlaams-Brussel Fonds" "OVO000132" "548966451")
    (<http://data.lblod.info/id/bestuurseenheden/2e7b53ef-d9f9-4c0c-9f41-0e63b24ed0f5> "2e7b53ef-d9f9-4c0c-9f41-0e63b24ed0f5" "Vlaamse Adviesraad voor Innoveren en Ondernemen" "OVO053996" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/f565fab7-695e-4cbe-8414-e0610a7f8327> "f565fab7-695e-4cbe-8414-e0610a7f8327" "Vlaamse Belastingdienst" "OVO000031" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/fe627027-ac62-4fd6-8bde-d3817968b1c0> "fe627027-ac62-4fd6-8bde-d3817968b1c0" "Vlaamse Dienst voor Arbeidsbemiddeling en Beroepsopleiding" "OVO000078" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/6367a09c-2510-4b8c-b3bb-aac178663338> "6367a09c-2510-4b8c-b3bb-aac178663338" "Vlaamse Gemeenschapscommissie" "OVO001151" "240682635")
    (<http://data.lblod.info/id/bestuurseenheden/432aca09-01a4-4348-a803-24493ef9e7b1> "432aca09-01a4-4348-a803-24493ef9e7b1" "Vlaamse Havens" "OVO000237" "834144867")
    (<http://data.lblod.info/id/bestuurseenheden/936d6add-40e3-4f29-a852-ae7d1221dddf> "936d6add-40e3-4f29-a852-ae7d1221dddf" "Vlaamse Herstelraad" "OVO001002" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/24594c0e-8513-49f2-a35b-f69805e8d866> "24594c0e-8513-49f2-a35b-f69805e8d866" "Vlaamse Hogescholenraad" "OVO000158" "650536537")
    (<http://data.lblod.info/id/bestuurseenheden/dbdeb4b0-a78f-440d-a209-f0a5509ed7d3> "dbdeb4b0-a78f-440d-a209-f0a5509ed7d3" "VLAAMSE INSTELLING VOOR TECHNOLOGISCH ONDERZOEK" "OVO000041" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/36e98508-53c0-4392-9e90-e55dd21864aa> "36e98508-53c0-4392-9e90-e55dd21864aa" "Vlaamse Interuniversitaire Raad" "OVO000157" "418766123")
    (<http://data.lblod.info/id/bestuurseenheden/e180d253-0834-40ef-88bd-532461a18534> "e180d253-0834-40ef-88bd-532461a18534" "VLAAMSE LANDMAATSCHAPPIJ" "OVO000094" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/ab5bc069-634d-42f6-af4f-82839ed2a018> "ab5bc069-634d-42f6-af4f-82839ed2a018" "VLAAMSE MAATSCHAPPIJ VOOR SOCIAAL WONEN" "OVO000103" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/af58f4c5-3300-4959-a2c1-c7f656aa09d0> "af58f4c5-3300-4959-a2c1-c7f656aa09d0" "Vlaamse Maatschappij voor Watervoorziening" "OVO000111" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8bd20e7b-5276-47b3-9a18-c525bb33c501> "8bd20e7b-5276-47b3-9a18-c525bb33c501" "VLAAMSE MILIEUMAATSCHAPPIJ" "OVO000092" "887290276")
    (<http://data.lblod.info/id/bestuurseenheden/7a619aad-4461-47ba-9ff4-4960cbb17f7e> "7a619aad-4461-47ba-9ff4-4960cbb17f7e" "Vlaamse Nutsregulator" "OVO000093" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/fe67948d-f0f4-463c-b98d-19627869cc2c> "fe67948d-f0f4-463c-b98d-19627869cc2c" "Vlaamse Ombudsdienst" "OVO000796" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/1c536a79-eaff-4cbb-8c99-d9dc4f3f4cd9> "1c536a79-eaff-4cbb-8c99-d9dc4f3f4cd9" "Vlaamse Onderwijsraad - Conseil flamand de l'Enseignement" "OVO000054" "249776285")
    (<http://data.lblod.info/id/bestuurseenheden/8eac5c62-b3ea-4ded-9338-9120043492d9> "8eac5c62-b3ea-4ded-9338-9120043492d9" "VLAAMSE PARTICIPATIEMAATSCHAPPIJ" "OVO000045" "461896677")
    (<http://data.lblod.info/id/bestuurseenheden/da935551-79c3-418f-925e-12e6612b49b6> "da935551-79c3-418f-925e-12e6612b49b6" "Vlaamse Raad voor Welzijn, Volksgezondheid en Gezin" "OVO050768" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/3247ad6d-9ecd-496f-a45b-1f83d0b727e8> "3247ad6d-9ecd-496f-a45b-1f83d0b727e8" "Vlaamse Regering" "OVO000729" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/bb9ee30b-75b5-4ad1-b2cf-e6d7b1f569d4> "bb9ee30b-75b5-4ad1-b2cf-e6d7b1f569d4" "VLAAMSE REGULATOR VOOR DE MEDIA" "OVO000071" "893159865")
    (<http://data.lblod.info/id/bestuurseenheden/270b35ce-c261-474a-b09b-d831a55263f7> "270b35ce-c261-474a-b09b-d831a55263f7" "Vlaamse Stichting voor Verkeerskunde" "OVO001726" "261150229")
    (<http://data.lblod.info/id/bestuurseenheden/0d99e40d-faa0-4fa1-91db-7cb09bbd38ff> "0d99e40d-faa0-4fa1-91db-7cb09bbd38ff" "Vlaamse toezichtcommissie voor de verwerking van persoonsgegevens" "OVO003237" "726689851")
    (<http://data.lblod.info/id/bestuurseenheden/ad51d699-35ef-49d5-8fda-b918aa75570e> "ad51d699-35ef-49d5-8fda-b918aa75570e" "VLAAMSE VERENIGING VOOR ICT-PERSONEEL" "OVO001845" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/738d48f6-65ae-41c2-9ba1-7c139374502f> "738d48f6-65ae-41c2-9ba1-7c139374502f" "Vlaamse Vervoermaatschappij - De Lijn" "OVO000100" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/1875c29a-4518-4e5c-bfb8-85ec42ba65f4> "1875c29a-4518-4e5c-bfb8-85ec42ba65f4" "VLAIO (Agentschap Innoveren & Ondernemen)" "OVO000039" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/ff6ea84a-96f0-4134-b5d2-cc6277991356> "ff6ea84a-96f0-4134-b5d2-cc6277991356" "vzw ‘de Rand’" "OVO001841" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/8fb3fd1f-5523-4fca-9542-7bb416c34a12> "8fb3fd1f-5523-4fca-9542-7bb416c34a12" "Wonen in Vlaanderen" "OVO000106" UNDEF)
    (<http://data.lblod.info/id/bestuurseenheden/507beea0-bbf8-459b-8cdf-513211d587aa> "507beea0-bbf8-459b-8cdf-513211d587aa" "Zuhal Demir, Vlaams minister van Onderwijs, Justitie en Werk" "OVO054211" UNDEF)
  }
  BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?uuid)) AS ?organizationGraph)
  FILTER NOT EXISTS {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?existing dct:identifier ?ovo .
    }
  }
}
