PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d89e882b-4f22-4d25-a63e-17eb246a18e2>
      rdf:type <http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode> ,
               <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode> ;
      skos:prefLabel "Vlaamse Overheid" ;
      mu:uuid "d89e882b-4f22-4d25-a63e-17eb246a18e2" .
  }
} ;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?uri org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d89e882b-4f22-4d25-a63e-17eb246a18e2> .
  }
}
WHERE {
  VALUES (?uri) {
    (<http://data.lblod.info/id/bestuurseenheden/9c18f402-7de3-40bd-be7d-95c4ee8d0ac6>)
    (<http://data.lblod.info/id/bestuurseenheden/36ad9ba3-1db9-4093-909c-2abcdd8191c0>)
    (<http://data.lblod.info/id/bestuurseenheden/bc6a98ef-e9c5-4da8-a54b-e980e187cb5a>)
    (<http://data.lblod.info/id/bestuurseenheden/f05fcea4-b4cb-4cfd-907f-a7c126980205>)
    (<http://data.lblod.info/id/bestuurseenheden/e3bf6d7e-6baa-4413-9fba-f6f374a2df2e>)
    (<http://data.lblod.info/id/bestuurseenheden/b55feb45-88c9-4500-9109-47cda44e9e9f>)
    (<http://data.lblod.info/id/bestuurseenheden/c838f08f-81c1-4fa3-a2c5-b6a0ef6816d9>)
    (<http://data.lblod.info/id/bestuurseenheden/4cbff7fe-8321-4858-a062-6e4eb69db165>)
    (<http://data.lblod.info/id/bestuurseenheden/152745a2-5d80-4e34-8b4c-f238be5713bc>)
    (<http://data.lblod.info/id/bestuurseenheden/2a5090c3-bc7a-4d6d-aa75-8203b86f796b>)
    (<http://data.lblod.info/id/bestuurseenheden/6a6f4f25-fc22-40a2-a9bd-fed533951c42>)
    (<http://data.lblod.info/id/bestuurseenheden/dcb02abc-5578-4f9b-a2b7-56648604e209>)
    (<http://data.lblod.info/id/bestuurseenheden/f1ba7005-86db-4a63-b37d-efb2df30e06d>)
    (<http://data.lblod.info/id/bestuurseenheden/37fcff1c-706d-401d-9cb2-06b4c5a84fcf>)
    (<http://data.lblod.info/id/bestuurseenheden/687b5161-a2c9-47fb-9ac4-565eecd39371>)
    (<http://data.lblod.info/id/bestuurseenheden/593c6a40-694d-4e22-b0f2-98f7483f4188>)
    (<http://data.lblod.info/id/bestuurseenheden/d7b0e8b4-6a6d-4a90-a701-d185fc998fb3>)
    (<http://data.lblod.info/id/bestuurseenheden/488ca2b5-4d50-43dd-b3d4-fff39d930b54>)
    (<http://data.lblod.info/id/bestuurseenheden/9c6f2923-f07f-4cb6-af89-e816c1a9b7ba>)
    (<http://data.lblod.info/id/bestuurseenheden/fb683350-14d5-41e2-bb87-8a4349a96f95>)
    (<http://data.lblod.info/id/bestuurseenheden/ca1c4692-5221-4590-8ab3-409ba1fa10bc>)
    (<http://data.lblod.info/id/bestuurseenheden/47f8c1f9-6d2e-428d-a829-c2c0ef5c5b80>)
    (<http://data.lblod.info/id/bestuurseenheden/b46f6a4d-1c82-4b76-ac40-da8b1599a157>)
    (<http://data.lblod.info/id/bestuurseenheden/643c500f-f110-4b83-89e3-f07eec92afcf>)
    (<http://data.lblod.info/id/bestuurseenheden/15867661-aa28-4f32-900f-0dbb588bf7cf>)
    (<http://data.lblod.info/id/bestuurseenheden/c9de797b-4101-49ec-819e-ae180c3c98b7>)
    (<http://data.lblod.info/id/bestuurseenheden/a1eb274c-b2a4-43e3-8064-3ba54ecb42c6>)
    (<http://data.lblod.info/id/bestuurseenheden/214def08-b058-431b-bfb6-2ce85db5b5be>)
    (<http://data.lblod.info/id/bestuurseenheden/00e66405-406e-4233-b209-1d4bd649314b>)
    (<http://data.lblod.info/id/bestuurseenheden/2e661c0a-10b1-4864-883e-5f440cdf43d1>)
    (<http://data.lblod.info/id/bestuurseenheden/ee020ae2-01ac-45a6-81c3-f338863c2638>)
    (<http://data.lblod.info/id/bestuurseenheden/99952177-ea35-4382-8b95-2f7bcf737b37>)
    (<http://data.lblod.info/id/bestuurseenheden/d6e7a2e8-1f65-42e9-8512-873871aa060c>)
    (<http://data.lblod.info/id/bestuurseenheden/d0445e29-5aeb-40b3-a5a1-96fa09d7d267>)
    (<http://data.lblod.info/id/bestuurseenheden/939c247b-4f32-4beb-94cc-d9a937dd61c5>)
    (<http://data.lblod.info/id/bestuurseenheden/38c2dbf4-7f11-43a3-9bf3-ed092557cb39>)
    (<http://data.lblod.info/id/bestuurseenheden/eef859ec-95fe-445e-b76f-b34e5e382501>)
    (<http://data.lblod.info/id/bestuurseenheden/750ce478-7c5d-4182-b804-d6c66ab48bb3>)
    (<http://data.lblod.info/id/bestuurseenheden/2c2c2791-81e5-4e12-8f44-29cd2c75db4c>)
    (<http://data.lblod.info/id/bestuurseenheden/77649b91-943d-4ac8-bc28-ecaf9b467fba>)
    (<http://data.lblod.info/id/bestuurseenheden/3e4e4786-6ffc-489c-87d8-51afd764709b>)
    (<http://data.lblod.info/id/bestuurseenheden/d5b7fbd2-2dc8-4a68-8b6b-b135c040d05e>)
    (<http://data.lblod.info/id/bestuurseenheden/a7938d00-3ecc-4d11-ae3f-7e7a0e15b6c1>)
    (<http://data.lblod.info/id/bestuurseenheden/6fb19b5b-f6ae-4a1f-b148-e389425fd385>)
    (<http://data.lblod.info/id/bestuurseenheden/f3779ec8-bc0c-4c5c-808f-e2499f1fdae6>)
    (<http://data.lblod.info/id/bestuurseenheden/65cc21be-5dfb-40ba-a314-f4ed52096afe>)
    (<http://data.lblod.info/id/bestuurseenheden/0349f3a0-cd22-4915-8bd7-34885d2d5507>)
    (<http://data.lblod.info/id/bestuurseenheden/90160a79-8e9e-4802-9c82-6cca74b64629>)
    (<http://data.lblod.info/id/bestuurseenheden/7d6d69ed-aa69-40b1-9b40-931eb1110581>)
    (<http://data.lblod.info/id/bestuurseenheden/f049f8c3-a580-4cd0-9387-e344543f9c12>)
    (<http://data.lblod.info/id/bestuurseenheden/8cc42bca-3909-436c-8cfb-bec97c2f8983>)
    (<http://data.lblod.info/id/bestuurseenheden/39e2afc7-2ea8-467a-b98f-2da42f3aae12>)
    (<http://data.lblod.info/id/bestuurseenheden/93b29e6c-3477-4281-8df9-2e7a93ad89b9>)
    (<http://data.lblod.info/id/bestuurseenheden/86cdd8ce-c0a4-44bd-a26f-df298414e5eb>)
    (<http://data.lblod.info/id/bestuurseenheden/dd11d1d1-2401-4bb3-b2c8-660adbca34f0>)
    (<http://data.lblod.info/id/bestuurseenheden/fefe37be-293e-4015-87df-72276e2e5d3f>)
    (<http://data.lblod.info/id/bestuurseenheden/7a2f747a-70f5-4bef-82f5-2818dc975d50>)
    (<http://data.lblod.info/id/bestuurseenheden/a7c5b9cc-fc34-4e15-83f2-a23bc153e791>)
    (<http://data.lblod.info/id/bestuurseenheden/3dcdd756-2a16-4ea4-a1fb-f819c7130577>)
    (<http://data.lblod.info/id/bestuurseenheden/aa5eeb43-2bb1-4519-bd31-e91351e6277b>)
    (<http://data.lblod.info/id/bestuurseenheden/d46db368-d7cf-4bab-a65e-844ebd47ba6b>)
    (<http://data.lblod.info/id/bestuurseenheden/385df42b-080c-445f-9805-21a4afe89a0e>)
    (<http://data.lblod.info/id/bestuurseenheden/018011fd-9c3e-4544-b7f7-ff4952eb0d7b>)
    (<http://data.lblod.info/id/bestuurseenheden/616fc045-e03e-4069-afe8-42ce8a5c6af9>)
    (<http://data.lblod.info/id/bestuurseenheden/68c38e9d-dc1c-4d40-8198-c52589a4dcb5>)
    (<http://data.lblod.info/id/bestuurseenheden/be99926a-8c19-48ff-b208-61f19797fcc5>)
    (<http://data.lblod.info/id/bestuurseenheden/bed1e74b-b83c-48f2-936e-ba573b81459c>)
    (<http://data.lblod.info/id/bestuurseenheden/d0cf2d24-33cc-4220-89e6-d8010580bae4>)
    (<http://data.lblod.info/id/bestuurseenheden/1fe215ee-c3ac-4853-881a-e1ac73e5b924>)
    (<http://data.lblod.info/id/bestuurseenheden/562da012-ad8a-4dab-b295-a7b556e433a7>)
    (<http://data.lblod.info/id/bestuurseenheden/b353498b-5189-4837-b2a1-ffb990efa131>)
    (<http://data.lblod.info/id/bestuurseenheden/eb37e38c-e94b-45f5-9b59-7b151175415f>)
    (<http://data.lblod.info/id/bestuurseenheden/210b2f38-78df-401a-837a-0a72cc3fe208>)
    (<http://data.lblod.info/id/bestuurseenheden/582da3eb-535e-48c7-a0bf-7c6ce12cbb91>)
    (<http://data.lblod.info/id/bestuurseenheden/d928bb68-2adf-4b02-a729-078d129d00b5>)
    (<http://data.lblod.info/id/bestuurseenheden/fb809dfd-62a3-487d-95b9-61d00fabd237>)
    (<http://data.lblod.info/id/bestuurseenheden/b47a2472-1ae6-418f-9732-ad891d3c3900>)
    (<http://data.lblod.info/id/bestuurseenheden/a3455b90-35a4-4c0d-bd41-037bfc57c415>)
    (<http://data.lblod.info/id/bestuurseenheden/83a3fa40-a448-48d3-be0c-756bef8b7b3a>)
    (<http://data.lblod.info/id/bestuurseenheden/ef4da7e4-6ad7-4b4c-92b5-95a173ebf296>)
    (<http://data.lblod.info/id/bestuurseenheden/13c9e66e-ad62-4229-83d9-4ca40042ea92>)
    (<http://data.lblod.info/id/bestuurseenheden/015d16f1-d674-4a09-acdf-ea492a1874af>)
    (<http://data.lblod.info/id/bestuurseenheden/de985d07-67f3-4463-97fc-9191b4992b49>)
    (<http://data.lblod.info/id/bestuurseenheden/bca445cf-072f-4e7d-8114-112e78979bb7>)
    (<http://data.lblod.info/id/bestuurseenheden/6629332b-2b08-4d06-964c-08fadfcd5478>)
    (<http://data.lblod.info/id/bestuurseenheden/065a1fd1-9795-4302-96ab-6a47dda4a92c>)
    (<http://data.lblod.info/id/bestuurseenheden/9163fb2c-10cd-421d-bc2b-cbe7d8b41210>)
    (<http://data.lblod.info/id/bestuurseenheden/c69b4b59-b458-470c-aa0e-a7f9915d8734>)
    (<http://data.lblod.info/id/bestuurseenheden/18b4cb27-1b21-4753-b9d3-977918e24c9f>)
    (<http://data.lblod.info/id/bestuurseenheden/b3e9c71d-ef29-4bb1-9721-9f35e9a04627>)
    (<http://data.lblod.info/id/bestuurseenheden/74d9b10c-08d9-4b26-ad1d-80ee4bbaeb2f>)
    (<http://data.lblod.info/id/bestuurseenheden/9e30e427-a42e-4fd4-83cc-24de4f09008d>)
    (<http://data.lblod.info/id/bestuurseenheden/65894071-2098-4c0e-a2c5-8bd72c6fd4bd>)
    (<http://data.lblod.info/id/bestuurseenheden/532881de-85e7-4a4b-9c87-174b7dcc14e2>)
    (<http://data.lblod.info/id/bestuurseenheden/398452e0-ca4f-427d-a731-cba55844c150>)
    (<http://data.lblod.info/id/bestuurseenheden/133cf710-3416-40fa-9750-f0e0c67610a9>)
    (<http://data.lblod.info/id/bestuurseenheden/6bb4bd04-611a-45cd-9465-c6e0a7831750>)
    (<http://data.lblod.info/id/bestuurseenheden/a44da519-a16b-4c70-9f05-674c5219941e>)
    (<http://data.lblod.info/id/bestuurseenheden/72b074e6-b9ab-4efc-a87e-d7c4f75f3c71>)
    (<http://data.lblod.info/id/bestuurseenheden/52749189-6c35-4832-b3de-91a6a73c2fb1>)
    (<http://data.lblod.info/id/bestuurseenheden/eb4e45d6-16bd-4aac-81f5-6555905bd257>)
    (<http://data.lblod.info/id/bestuurseenheden/8f014af8-b3fe-4886-b10f-567262addb1b>)
    (<http://data.lblod.info/id/bestuurseenheden/18a9a64f-03d3-4aaa-ae05-91f0a280c2f1>)
    (<http://data.lblod.info/id/bestuurseenheden/cc9ecd16-87b5-43fb-99b4-70a30d9e1b89>)
    (<http://data.lblod.info/id/bestuurseenheden/9c259927-8249-4996-93f1-c74cc0e8a5b4>)
    (<http://data.lblod.info/id/bestuurseenheden/b937df13-8e96-42e5-81f9-14ad4c5d4821>)
    (<http://data.lblod.info/id/bestuurseenheden/150f0931-e91f-479f-9997-0be012e728cc>)
    (<http://data.lblod.info/id/bestuurseenheden/1f7fb100-cf2c-4e50-9e36-999ac45a6e30>)
    (<http://data.lblod.info/id/bestuurseenheden/b0242c37-c8f4-4f6f-a67b-9d5cfacf74c8>)
    (<http://data.lblod.info/id/bestuurseenheden/b5e286ce-86cc-4a03-b4e7-8eaca4ff00e6>)
    (<http://data.lblod.info/id/bestuurseenheden/be635f3f-3dca-46da-93d8-fff0da8d27c9>)
    (<http://data.lblod.info/id/bestuurseenheden/8ac70fc2-4459-4427-b24d-6c7d467ac4d1>)
    (<http://data.lblod.info/id/bestuurseenheden/7f30b948-214c-491e-ab26-68f4e92b94c5>)
    (<http://data.lblod.info/id/bestuurseenheden/ee0da6c1-d177-45ad-bdf6-0b7b07c6ea2e>)
    (<http://data.lblod.info/id/bestuurseenheden/90f5a3a1-bb8b-4402-ba01-48163793608b>)
    (<http://data.lblod.info/id/bestuurseenheden/57fe0824-0652-407f-ba9a-025fd40e4002>)
    (<http://data.lblod.info/id/bestuurseenheden/bc112e5f-cb1c-4823-93d0-bea83a8b3e24>)
    (<http://data.lblod.info/id/bestuurseenheden/bb23ff6c-2239-40ce-a461-bd9ce34c0d07>)
    (<http://data.lblod.info/id/bestuurseenheden/7e1ddc77-efcf-4980-9cdf-7db8fad71698>)
    (<http://data.lblod.info/id/bestuurseenheden/b441f9ce-d912-41a1-aa24-850dcc131b24>)
    (<http://data.lblod.info/id/bestuurseenheden/fc114256-4b55-4396-913e-6632b68fd35b>)
    (<http://data.lblod.info/id/bestuurseenheden/66f9802e-78c7-4320-aeb9-d4273f6bee88>)
    (<http://data.lblod.info/id/bestuurseenheden/693a1573-a3f2-4a35-8bca-68e9d6a1a070>)
    (<http://data.lblod.info/id/bestuurseenheden/009ba3f7-8125-4296-91d2-3f621837a05a>)
    (<http://data.lblod.info/id/bestuurseenheden/ff452b85-b3e5-4bc8-9030-34d5ecd4fd38>)
    (<http://data.lblod.info/id/bestuurseenheden/58e203f8-82b7-4039-b4ad-7a00c44d907c>)
    (<http://data.lblod.info/id/bestuurseenheden/db254fa7-15ea-4d18-8cae-70f8079c58d7>)
    (<http://data.lblod.info/id/bestuurseenheden/5f018924-899c-40bd-b339-15275cd18275>)
    (<http://data.lblod.info/id/bestuurseenheden/0a3a1491-9872-4aa0-948e-be1ae98dffab>)
    (<http://data.lblod.info/id/bestuurseenheden/adfeffbb-adbe-4e15-9000-0ff4564766b2>)
    (<http://data.lblod.info/id/bestuurseenheden/ad6c35bd-2958-445c-b4e7-5798464610f2>)
    (<http://data.lblod.info/id/bestuurseenheden/d2d9fc4e-9e9f-4235-b916-88809595c24b>)
    (<http://data.lblod.info/id/bestuurseenheden/68ffb5f4-edf0-463e-97f6-67256607ea8c>)
    (<http://data.lblod.info/id/bestuurseenheden/73461be2-364f-475c-b4b0-fe7ba6bbcf20>)
    (<http://data.lblod.info/id/bestuurseenheden/c3a45003-c1bd-45e6-8ba9-69936b3b4d7c>)
    (<http://data.lblod.info/id/bestuurseenheden/1fa4926f-27c2-4cfb-beaa-b8077312dfcc>)
    (<http://data.lblod.info/id/bestuurseenheden/e39681bb-84d9-49bf-8309-af47660dfe67>)
    (<http://data.lblod.info/id/bestuurseenheden/bd4ae99b-5e43-40c8-89da-f924d3da5524>)
    (<http://data.lblod.info/id/bestuurseenheden/85d5d169-fc49-4fa9-9402-e7ce4d6fa527>)
    (<http://data.lblod.info/id/bestuurseenheden/96c615f2-a0cf-45a5-993e-60529c143676>)
    (<http://data.lblod.info/id/bestuurseenheden/a1985ede-9bf9-4702-aecb-8aa95ff491c4>)
    (<http://data.lblod.info/id/bestuurseenheden/b48834ad-2323-406d-a890-d3f0ce572bd7>)
    (<http://data.lblod.info/id/bestuurseenheden/aef1b807-7419-4653-b9ba-b1f92de227ae>)
    (<http://data.lblod.info/id/bestuurseenheden/d4dcdac9-1c04-4e67-9b3a-0477c945a8b1>)
    (<http://data.lblod.info/id/bestuurseenheden/fd203f35-e946-4750-a95b-35e0e4a87cc8>)
    (<http://data.lblod.info/id/bestuurseenheden/aed79fd6-7437-4a8d-b968-072e432d5430>)
    (<http://data.lblod.info/id/bestuurseenheden/e6bf9a82-211f-4707-bd91-1bad1d89ef3f>)
    (<http://data.lblod.info/id/bestuurseenheden/eed6be77-a5d3-4c2e-a784-1618f4ac3b02>)
    (<http://data.lblod.info/id/bestuurseenheden/2cd54973-3f3e-45c8-848c-c29580def8b1>)
    (<http://data.lblod.info/id/bestuurseenheden/c5146b00-fbd5-4b9d-96ee-55b92f734259>)
    (<http://data.lblod.info/id/bestuurseenheden/8d33fce8-84a4-481b-965b-851081f204a0>)
    (<http://data.lblod.info/id/bestuurseenheden/3d463078-0e76-4d31-9d45-cd4591c924f5>)
    (<http://data.lblod.info/id/bestuurseenheden/2ecb8a46-8997-4412-aa3a-972f2beb9c55>)
    (<http://data.lblod.info/id/bestuurseenheden/3842ff59-3829-4e1e-bbc6-daec9edb4b8b>)
    (<http://data.lblod.info/id/bestuurseenheden/a1301b1a-61b2-4f6c-9971-39cfa421326f>)
    (<http://data.lblod.info/id/bestuurseenheden/bdffb035-7998-4626-ac0e-c43502239022>)
    (<http://data.lblod.info/id/bestuurseenheden/2aca3a79-7e86-4632-8f2b-36f681cd4f88>)
    (<http://data.lblod.info/id/bestuurseenheden/d278898c-4774-4feb-9cec-a1d6ecee57bb>)
    (<http://data.lblod.info/id/bestuurseenheden/fb53f8b6-ffd6-4c47-8850-226c81fe188b>)
    (<http://data.lblod.info/id/bestuurseenheden/60a11431-278f-4dd3-8f03-0b09f5340b58>)
    (<http://data.lblod.info/id/bestuurseenheden/2e7b53ef-d9f9-4c0c-9f41-0e63b24ed0f5>)
    (<http://data.lblod.info/id/bestuurseenheden/7c2dda27-e4c0-4749-bf7e-f76c6c38d032>)
    (<http://data.lblod.info/id/bestuurseenheden/79c5a8e5-50ca-4d41-bed3-0109a49c0101>)
    (<http://data.lblod.info/id/bestuurseenheden/3ca6331e-ac01-4b0b-81c4-39cb1fca5c3b>)
    (<http://data.lblod.info/id/bestuurseenheden/53f2aa0e-8562-44da-a926-9871822930e3>)
    (<http://data.lblod.info/id/bestuurseenheden/46526f3c-2081-461d-aeb7-c5c484aa7321>)
    (<http://data.lblod.info/id/bestuurseenheden/efc39d87-2179-43ac-bd08-02079b88adee>)
    (<http://data.lblod.info/id/bestuurseenheden/e7619af3-a504-4d79-bd1e-02d867f92f82>)
    (<http://data.lblod.info/id/bestuurseenheden/0273576e-ff1c-41fb-9043-d9eaf90e0303>)
    (<http://data.lblod.info/id/bestuurseenheden/04e24292-0eac-4c96-87a2-28ff6e994840>)
    (<http://data.lblod.info/id/bestuurseenheden/76c8fb6b-4337-4990-acb1-10f225b6eb1e>)
    (<http://data.lblod.info/id/bestuurseenheden/f64c5c5b-791a-4178-9e2d-83ff0700e662>)
    (<http://data.lblod.info/id/bestuurseenheden/f93dfb47-3eeb-4a7a-82bb-0e8b2f71eede>)
    (<http://data.lblod.info/id/bestuurseenheden/f5f930f3-7e61-41cd-a2e9-1cf7a33a03e2>)
    (<http://data.lblod.info/id/bestuurseenheden/a69bc0ae-cdd5-43b1-b902-594c95ee846d>)
    (<http://data.lblod.info/id/bestuurseenheden/d8774565-a776-47a7-ac3d-3c30dd99e0d6>)
    (<http://data.lblod.info/id/bestuurseenheden/72ec5dcc-322e-43d7-b5ca-a23a8ddf6fbd>)
    (<http://data.lblod.info/id/bestuurseenheden/da935551-79c3-418f-925e-12e6612b49b6>)
    (<http://data.lblod.info/id/bestuurseenheden/3247ad6d-9ecd-496f-a45b-1f83d0b727e8>)
    (<http://data.lblod.info/id/bestuurseenheden/cdc8d1a4-9f48-4ae2-aa4a-2e5b3a61e4ea>)
    (<http://data.lblod.info/id/bestuurseenheden/0549e664-869f-40fd-8141-b79e1a53f877>)
    (<http://data.lblod.info/id/bestuurseenheden/6208e1c5-e8ea-4377-8ffe-935172b6531e>)
    (<http://data.lblod.info/id/bestuurseenheden/ad51d699-35ef-49d5-8fda-b918aa75570e>)
    (<http://data.lblod.info/id/bestuurseenheden/e9c202d2-cc07-4104-b1ee-3d2c4850744e>)
    (<http://data.lblod.info/id/bestuurseenheden/0cf34be8-7c6d-4634-8c94-8a1d26a698a1>)
    (<http://data.lblod.info/id/bestuurseenheden/f06e1091-63a8-487d-b157-d31bb3f18aa4>)
    (<http://data.lblod.info/id/bestuurseenheden/394c20f5-e39a-4889-b19e-a27439d1ae5b>)
    (<http://data.lblod.info/id/bestuurseenheden/507beea0-bbf8-459b-8cdf-513211d587aa>)
  }
}
