PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX schema: <http://schema.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>


CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a schema:ContactPoint;
    ?p ?o.

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    schema:email,
    schema:telephone,
    schema:contactType,
    foaf:page
  ))
}